export const discordHref = 'https://discord.gg/E3xpc2ZhFP'
export const githubHref = 'https://github.com/ERCWizard'
export const twitterHref = 'https://twitter.com/ERCWizard'
export const producthuntHref = 'https://www.producthunt.com/products/erc-wizard'
export const ercWizardHref = 'https://ercwizard.com/'
export const ercWizardDocsHref = 'https://docs.ercwizard.com/'
