export const discordHref = 'https://discord.gg/E3xpc2ZhFP'
export const githubHref = 'https://github.com/ERCWizard'
export const twitterHref = 'https://twitter.com/ERCWizard'
export const producthuntHref = 'https://www.producthunt.com/products/erc-wizard'
export const ercWizardAppHref = 'https://app.ercwizard.com/'
